# -*- coding: utf-8 -*-
"""PyProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dw0tRR21mxVXiIdJQNIdzkca0j2An1AK
"""

import requests

API_BASE_URL = "https://www.projectabcd.com/api/getinfo.php?id="

sheroes_id_list = [761, 762, 763, 764, 765, 766, 767, 768]

'''
Fetch the json data from API
The data_list is a list of dictionaries where each dictionary encapsulates the details of an ID.
'''
def fetch_data_from_api(ids=sheroes_id_list):
    data_list = []
    for id in ids:
        url = API_BASE_URL + str(id)
        headers = {
            "Accept": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
        }

        response = requests.get(url, headers=headers)

        if response.status_code == 200:
            data_list.append(response.json()['data'])
        else:
            print(f"Failed to get data from the API for ID {id}. Status code:", response.status_code)

    return data_list

data_list = fetch_data_from_api()

html_table = """
<table border="1">
    <tr>
        <th>Serial</th>
        <th>ABC_ID</th>
        <th>Name</th>
        <th>Description length</th>
        <th>Did you know length</th>
        <th>Total length</th>
    </tr>
"""

for index, data in enumerate(data_list, start=1):
    abc_id = data.get("id", "")
    name = data.get("name", "")
    description = data.get("description", "")
    did_you_know = data.get("did_you_know", "")
    description_length = len(description)
    did_you_know_length = len(did_you_know)
    total_length = description_length + did_you_know_length

    html_table += f"""
    <tr>
        <td>{index}</td>
        <td>{abc_id}</td>
        <td>{name}</td>
        <td>{description_length}</td>
        <td>{did_you_know_length}</td>
        <td>{total_length}</td>
    </tr>
    """

html_table += "</table>"

print(html_table)